Repository Kernel-GL-HRK/gl-kernel-training-2019, pull requests merged in 2019-10, with the labels that each got.

#13 02 git solution
  02-Git/README.md
  02-Git/solution/Makefile
  02-Git/solution/main.c
Labels: OK

#4 02-Git
  02-Git/Makefile
  02-Git/README.md
  02-Git/main.c
Labels: OK

#7 02 git solution
  02-Git/Makefile
  02-Git/README.md
  02-Git/task2.c
Labels: OK

#8 Home work lesson2
  02-Git/README.md
  02-Git/main.c
  02-Git/makefile
Labels: OK

#10 02 git solution
  02-Git/README.md
  02-Git/Solution/.directory
  02-Git/Solution/main.c
  02-Git/Solution/makefile
Labels: OK

#14 02 git solution
  02-Git/Makefile
  02-Git/README.md
  02-Git/main.c
Labels: OK

#9 02 git solution
  02-Git/Makefile
  02-Git/README.md
  02-Git/main.c
Labels: OK

#15 02 git feature rock paper scissors
  02-Git/Dummy_Program.c
  02-Git/Game.c
  02-Git/README.md
  02-Git/makefile
Labels: OK

#11 02 git task
  02-Git/Makefile
  02-Git/main.c
Labels: OK

#19 03-bash: script for finding duplicate files
  03-Bash/find_dup_files/find_dup_files.sh
Labels: OK

#18 03 git task: Add script for fix owner
  03-Bash/fix_owner/fix_owner.sh
Labels: ready

#23 Solution 03 bash find dup files
  03-Bash/README.md
  03-Bash/find_dup_files/README.md
  03-Bash/find_dup_files/find_dup_files.sh
  03-Bash/fix_owner/README.md
  03-Bash/kernel_git/README.md
Labels: OK

#21 03 bash 1
  03-Bash/find_dup_files/find_dup_files.sh
Labels: OK

#24 03 bash find dup files
  03-Bash/find_dup_files/find_dup_files.sh
Labels: OK

#39 Home work lesson03 find dup files
  03-Bash/README.md
  03-Bash/find_dup_files/README.md
  03-Bash/find_dup_files/find_dup_files.sh
  03-Bash/fix_owner/README.md
  03-Bash/kernel_git/README.md
Labels: OK

#36 03 bash find dup files script
  03-Bash/find_dup_files/README.md
  03-Bash/find_dup_files/find_dup_files.sh
Labels: OK

#33 03 bash hw 1
  03-Bash/README.md
  03-Bash/find_dup_files/README.md
  03-Bash/fix_owner/README.md
  03-Bash/fix_owner/fix_owner.sh
  03-Bash/kernel_git/README.md
Labels: OK

#26 03-Bash_kernel_git: Add statistics calculation script
  03-Bash/kernel_git/kernel_stats.sh
Labels: OK

#29 03 bash kernel git
  03-Bash/kernel_git/kernel_stats.sh
Labels: OK

#44 Update homework tasks bash kernel 01
  03-Bash/README.md
  03-Bash/find_dup_files/README.md
  03-Bash/fix_owner/README.md
  03-Bash/kernel_git/README.md
  03-Make/README.md
  03-Make/make_email/Makefile
  03-Make/make_simplest/Makefile
  03-Make/make_simplest/main.c
  04-KernelModule/README.md
Labels: ready

#35 03 bash fix owner script
  03-Bash/fix_owner/README.md
  03-Bash/fix_owner/fix_owner.sh
Labels: OK

#40 03 bash fix owner solution
  03-Bash/README.md
  03-Bash/find_dup_files/README.md
  03-Bash/fix_owner/README.md
  03-Bash/fix_owner/fix_owner.sh
  03-Bash/kernel_git/README.md
Labels: OK

#43 03 bash fix owner
  03-Bash/fix_owner/fix_owner.sh
Labels: OK

#41 03 bash find duplicate files solution
  03-Bash/find_dup_files/find_dup_files.sh
Labels: ready

#30 Home work kernel git 03
  03-Bash/kernel_git/kernel_hm.sh
Labels: OK

#22 03 bash 2
  03-Bash/fix_owner/fix_owner.sh
Labels: ready

#27 03-Bash-3: Add kernel statistics script
  03-Bash/kernel_git/kernel_stats.sh
Labels: ready

#17 03-Bash: Add find_dup_files.sh
  03-Bash/find_dup_files/find_dup_files.sh
Labels: ready

#25 03-Bash: Add fix_owner.sh
  03-Bash/fix_owner/fix_owner.sh
Labels: OK

#42 03 bash kernel git stat solution
  03-Bash/kernel_git/kernel_stats.sh
Labels: ready

#38 03 bash kernel stats script
  03-Bash/kernel_git/README.md
  03-Bash/kernel_git/kernel_stats.sh
Labels: OK

#37 03-Bash
  03-Bash/find_dup_files/find_dup_files.sh
  03-Bash/fix_owner/fix_owner.sh
  03-Bash/kernel_git/kernel_stats.sh
Labels: ready

#47 Bash 03 hw task 1 fix owner ver 2
  03-Bash/fix_owner/fix_owner.sh
Labels: ready

#45 Bash 03 hw task 1 fix owner
  03-Bash/fix_owner/fix_owner.sh
Labels: changes requested

#57 03 make
  03-Make/make_simplest/Makefile
  03-Make/make_soup/Makefile
Labels: OK

#54 03-Make
  03-Make/make_simplest/Makefile
  03-Make/soup/Makefile
  03-Make/soup/grocery/products/bay_leaf.txt
  03-Make/soup/grocery/products/carrot.txt
  03-Make/soup/grocery/products/oil.txt
  03-Make/soup/grocery/products/onion.txt
  03-Make/soup/grocery/products/pea.txt
  03-Make/soup/grocery/products/pepper.txt
  03-Make/soup/grocery/products/potato.txt
  03-Make/soup/grocery/products/salt.txt
  03-Make/soup/grocery/products/smoked_pork_ribs.txt
  03-Make/soup/grocery/products_list.sh
  03-Make/soup/kitchen/stove/add_pea.sh
  03-Make/soup/kitchen/stove/add_spice.sh
  03-Make/soup/kitchen/stove/bouillon.sh
  03-Make/soup/kitchen/stove/fry_onion_and_carrot.sh
  03-Make/soup/kitchen/table/dunk_pea.sh
  03-Make/soup/kitchen/table/slice_onion_and_carrot.sh
  03-Make/soup/kitchen/table/slice_potato.sh
  03-Make/soup/misc/actions_title.sh
  03-Make/soup/misc/create_no_make_script.sh
  03-Make/soup/misc/title.sh
Labels: ready

#48 04_KernelModule
  04-KernelModule/Makefile
  04-KernelModule/dmesg.txt
  04-KernelModule/mymodule.c
Labels: OK

#50 04-KernelModule: Add first version of home work
  04-KernelModule/Makefile
  04-KernelModule/dmesg.txt
  04-KernelModule/mymodule.c
Labels: OK

#51 04 kernel module: Add a simple kernel module
  04-KernelModule/Log of dmesg/Log.png
  04-KernelModule/Log of dmesg/dmesg.txt
  04-KernelModule/Makefile
  04-KernelModule/test_module.c
Labels: OK

#58 04 kernel module
  04-KernelModule/Makefile
  04-KernelModule/README.md
  04-KernelModule/log.txt
  04-KernelModule/mymodule.c
Labels: OK

#56 Hm lesson03 make
  03-Make/Cooking/Makefile
  03-Make/Cooking/buy_food_from_market.sh
  03-Make/Cooking/create_res.sh
  03-Make/Cooking/get_water_from_faucet.sh
  03-Make/Cooking/ready.sh
  03-Make/make_simplest/Makefile
Labels: OK

#65 03 make solution
  03-Make/README.md
  03-Make/make_email/Makefile
  03-Make/make_simplest/Makefile
  03-Make/make_simplest/main.c
  03-Make/make_soup/Makefile
  03-Make/make_soup/data/shop/carrot.txt
  03-Make/make_soup/data/shop/meat.txt
  03-Make/make_soup/data/shop/onion.txt
  03-Make/make_soup/data/shop/potato.txt
  03-Make/make_soup/data/shop/solt.txt
  03-Make/make_soup/data/shop/water.txt
  03-Make/make_soup/scripts/cooksoup.sh
  03-Make/make_soup/scripts/cutweg.sh
  03-Make/make_soup/scripts/deleteProgresFiles.sh
  03-Make/make_soup/scripts/fry.sh
  03-Make/make_soup/scripts/getFromShop.sh
Labels: ready

#63 03 make solution
  03-Make/Makefile
  03-Make/README.md
  03-Make/make_email/Makefile
  03-Make/make_simplest/Makefile
  03-Make/make_simplest/main.c
Labels: OK

#60 03 make task
  03-Make/make_simplest/Makefile
  03-Make/make_soup/Makefile
  03-Make/make_soup/buy.sh
  03-Make/make_soup/script_nomake.sh
  03-Make/make_soup/slice.sh
  03-Make/make_soup/water.sh
Labels: ready

#55 Solution 03 make
  03-Make/README.md
  03-Make/make_email/Makefile
  03-Make/make_simplest/Makefile
  03-Make/make_simplest/main.c
  03-Make/make_soup/Makefile
  03-Make/make_soup/action.sh
Labels: ready

#49 03 make
  03-Make/make_simplest/Makefile
  03-Make/make_soup/Makefile
Labels: ready

#59 04-KernelModule: Add simple module
  04-KernelModule/Makefile
  04-KernelModule/log.txt
  04-KernelModule/mymodule.c
Labels: OK

#61 03-Make
  03-Make/make_simplest/Makefile
  03-Make/soup/Makefile
  03-Make/soup/check_dirs.sh
  03-Make/soup/get_water_from_faucet.sh
Labels: OK

#66 04-KernelModule: Add implementation of a simple module
  04-KernelModule/Makefile
  04-KernelModule/dmesg.txt
  04-KernelModule/mymodule.c
Labels: OK

#70 04 kernel module solution
  04-KernelModule/Makefile
  04-KernelModule/README.md
  04-KernelModule/log.txt
  04-KernelModule/mymodule.c
Labels: OK

#72 04-Kernel: Implement simple module
  04-KernelModule/Makefile
  04-KernelModule/log_1.txt
  04-KernelModule/simple_module.c
Labels: OK

#67 Hm lesson04 kernel
  04-KernelModule/README.md
  04-KernelModule/vp_module/Makefile
  04-KernelModule/vp_module/vp_module.c
  04-KernelModule/vp_module/vp_module_err.log
  04-KernelModule/vp_module/vp_module_ok.log
Labels: OK

#52 Bash 03 hw task 2 find dup files
  03-Bash/find_dup_files/find_dup_files.sh
Labels: ready

#68 Make 03 hw task 0 fix logical error in project make simplest
  03-Make/make_simplest/Makefile
Labels: ready

#69 04 kernel module solution
  04-KernelModule/README.md
  04-KernelModule/checkpatch.pl
  04-KernelModule/log.md
  04-KernelModule/simp_mod.c
Labels: OK

#64 Solution 04 kernel module
  04-KernelModule/Makefile
  04-KernelModule/README.md
  04-KernelModule/error.log
  04-KernelModule/module_04.c
  04-KernelModule/ok.log
Labels: OK

#62 03-Make: Add recipe for soup
  03-Make/make_simplest/Makefile
  03-Make/soup/Makefile
  03-Make/soup/create_dir.sh
  03-Make/soup/delete_dir.sh
  03-Make/soup/prepare_pot.sh
  03-Make/soup/prepare_soup.sh
Labels: ready
