Repository Kernel-GL-HRK/gl-kernel-training-2019, pull requests merged in 2019-12, with the labels that each got.

#125 mpu6050_test: Add script to read temperature
  Practice_01-mpu6050/README_mpu6050.md
  Practice_01-mpu6050/logs/log_1.png
  Practice_01-mpu6050/logs/log_2.png
  Practice_01-mpu6050/logs/log_for_script
  Practice_01-mpu6050/logs/log_for_script.png
  Practice_01-mpu6050/logs/log_for_script_1.png
  Practice_01-mpu6050/logs/log_test_mpu6050
  Practice_01-mpu6050/mpu6050_user/mpu6050_script.sh
Labels: OK

#118 07 memory management module
  07-MemoryManagement/module/Makefile
  07-MemoryManagement/module/mymodule.c
  07-MemoryManagement/module/result/get_free_pages.txt
  07-MemoryManagement/module/result/kmalloc.txt
  07-MemoryManagement/module/result/kzalloc.txt
  07-MemoryManagement/module/result/vmalloc.txt
Labels: OK

#132 09-DeviceTree: Add kernel module to device tree testing
  09-DeviceTree/DT_overlay/sun8i-h3-i2c-mpu6050.dtbo
  09-DeviceTree/DT_overlay/sun8i-h3-i2c-mpu6050.dts
  09-DeviceTree/kernel_module/Makefile
  09-DeviceTree/kernel_module/mpu6050_overlay_test.c
  09-DeviceTree/logs/dmesg
  09-DeviceTree/logs/dmesg.png
  09-DeviceTree/logs/log
  09-DeviceTree/logs/log.png
Labels: ready

#128 Mpu6050 user
  mpu6050_user/Makefile
  mpu6050_user/README.md
  mpu6050_user/mpu6050.c
  mpu6050_user/result.txt
Labels: OK

#133 09-Device_tree_fake_module
  09-DeviceTree/Makefile
  09-DeviceTree/README.md
  09-DeviceTree/dtsi/fake_module.dtsi
  09-DeviceTree/fake_module.c
  09-DeviceTree/result/dmesg.txt
  09-DeviceTree/result/lsmod.txt
  09-DeviceTree/result/start_u-boot.txt
Labels: changes requested

#134 Add: script for printing temperature from MPU6050
  08-MPU6050/log.log
  08-MPU6050/temperature.sh
Labels: OK

#131 Practice 01 mpu6050
  Practice_01_mpu6050/mpu6050_user/README_mpu6050.md
  Practice_01_mpu6050/mpu6050_user/log.txt
  Practice_01_mpu6050/mpu6050_user/run.sh
Labels: OK

#141 08-TemperatureMeasurementMPU6050
  08-ScriptReadTempMPU6050/read_temp_mpu6050.sh
  08-ScriptReadTempMPU6050/result
Labels: OK

#144 09 Device Tree
  09-DeviceTree/Homework.md
  09-DeviceTree/auto_loadable_module/Makefile
  09-DeviceTree/auto_loadable_module/auto_loadable_module.c
  09-DeviceTree/auto_loadable_module/overlays/auto_loadable_module.dtsi
  09-DeviceTree/log_dmesg
  09-DeviceTree/log_system_loading
Labels: OK

#127 mpu6050_user: Add read temperature from mpu6050
  Practice_I_MPU6050/README.md
  Practice_I_MPU6050/mpu6050_user/Makefile
  Practice_I_MPU6050/mpu6050_user/data.dat
  Practice_I_MPU6050/mpu6050_user/graphic.txt
  Practice_I_MPU6050/mpu6050_user/log.jpeg
  Practice_I_MPU6050/mpu6050_user/mpu6050_user.c
  Practice_I_MPU6050/mpu6050_user/run.sh
  Practice_I_MPU6050/mpu6050_user/test_speed.log
  Practice_I_MPU6050/mpu6050_user/test_speed.sh
Labels: OK

#138 08_fake_module: Add fake module and device tree overlay
  MPU6050/fake_module/Makefile
  MPU6050/fake_module/log.txt
  MPU6050/fake_module/module_fake_08.c
  MPU6050/fake_module/sun8i-h3-fake.dts
Labels: OK

#112 Solution 07 Memory Management module
  07-MemoryManagement/module/Makefile
  07-MemoryManagement/module/module_07.c
  07-MemoryManagement/module/start_tests.sh
  07-MemoryManagement/module/x86_64_out.txt
  07-MemoryManagement/module/x86_64_out.txt.pdf
Labels: OK

#148 09-TestDeviceTree
  09-TestModule/Makefile
  09-TestModule/log.log
  09-TestModule/sun8i-h3-test.dts
  09-TestModule/test_module.c
Labels: OK

#140 Mpu6050
  mpu6050/improved-results.txt
  mpu6050/mpu6050.c
  mpu6050/perfomance_check/Makefile
  mpu6050/perfomance_check/checking_performance
  mpu6050/perfomance_check/main.c
  mpu6050/results.txt
  mpu6050/sun8i-h3-mpu6050.dts
Labels: OK

#136 Hm 09 overlay
  09-DeviceTree/dts_overlay/linux_log.txt
  09-DeviceTree/dts_overlay/my_dummy_overlay.dts
  09-DeviceTree/dummy_module/Makefile
  09-DeviceTree/dummy_module/dummy_module.c
  09-DeviceTree/dummy_module/env_setup.sh
Labels: OK

#142 Mpu6050 module
  mpu6050/Makefile
  mpu6050/README.md
  mpu6050/doc/MPU-6000-Register-Map1.pdf
  mpu6050/doc/MPU-6050_DataSheet_V3 4.pdf
  mpu6050/doc/PS-MPU-6000A.pdf
  mpu6050/dtsi/mpu6050.dtsi
  mpu6050/mpu6050-regs.h
  mpu6050/mpu6050.c
  mpu6050/result/dmesg.txt
  mpu6050/result/readsysfs.txt
  mpu6050/result/start_u-boot.txt
  mpu6050/result/test-mod.txt
  mpu6050/test-mod.c
Labels: OK

#135 mpu6050: Add fixes to kernel module and program to check performance
  mpu6050/logs/dmesg
  mpu6050/logs/log
  mpu6050/logs/performance_after_optimization
  mpu6050/logs/performance_before_optimization
  mpu6050/mpu6050.c
  mpu6050/performance_checking_program/Makefile
  mpu6050/performance_checking_program/checking_performance
  mpu6050/performance_checking_program/main.c
  mpu6050/performance_checking_program/main.h
  mpu6050/sun8i-h3-orangepi-one.dts
Labels: OK
